version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3556:3556"
    environment:
      MONGO_URI: ${MONGO_URI} 
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3556", "--reload"]